GET http://127.0.0.1:8000/meals/

###

GET http://127.0.0.1:8000/meals/2

###


POST http://127.0.0.1:8000/meals/ HTTP/1.1

content-type: application/json
  {
    "name": "Chicken",
    "meal_type": "Dinner"
  }
  
###


DELETE http://127.0.0.1:8000/meals/3 HTTP/1.1

content-type: application/json



###